Repository istio/common-files, pull requests merged in 2019-09, with the labels that each got.

#51 Add support to lint the common files.
  Makefile
  files/common/Makefile.common.mk
Labels: cla: yes, size/S

#52 Add a standard .gitattributes file.
  files/.gitattributes
Labels: cla: yes, size/XS

#53 Fix copy command so it copies the hidden .gitattributes file correctly.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#54 Fix extra space
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#56 Argh. Testing leftovers...
  Makefile
Labels: cla: yes, size/XS

#57 Add support for linting and formatting protos.
  files/Makefile
  files/common/Makefile.common.mk
Labels: cla: yes, size/S

#59 Add .github to the list of directories we skip during linting
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#60 Added missing gogo protos.
  Makefile
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/any.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/api.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/compiler/plugin.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/duration.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/empty.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/field_mask.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/source_context.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/struct.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/timestamp.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/type.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/wrappers.proto
  common-protos/k8s.io/api/admissionregistration/v1/generated.proto
  common-protos/k8s.io/api/admissionregistration/v1beta1/generated.proto
  common-protos/k8s.io/api/apps/v1/generated.proto
  common-protos/k8s.io/api/apps/v1beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta2/generated.proto
  common-protos/k8s.io/api/batch/v1/generated.proto
  common-protos/k8s.io/api/batch/v1beta1/generated.proto
  common-protos/k8s.io/api/batch/v2alpha1/generated.proto
  common-protos/k8s.io/api/coordination/v1/generated.proto
  common-protos/k8s.io/api/coordination/v1beta1/generated.proto
  common-protos/k8s.io/api/core/v1/generated.proto
  common-protos/k8s.io/api/events/v1beta1/generated.proto
  common-protos/k8s.io/api/networking/v1beta1/generated.proto
  common-protos/k8s.io/api/node/v1alpha1/generated.proto
  common-protos/k8s.io/api/node/v1beta1/generated.proto
  common-protos/k8s.io/api/policy/v1beta1/generated.proto
  common-protos/k8s.io/api/scheduling/v1/generated.proto
  common-protos/k8s.io/api/scheduling/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1/generated.proto
  common-protos/k8s.io/api/storage/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1beta1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/api/resource/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto
  get_protos.sh
Labels: cla: yes, size/XXL

#61 Fix .PHONY targets
  files/Makefile
Labels: cla: yes, size/XS

#63 Revert "Fix .PHONY targets"
  files/Makefile
Labels: cla: yes, size/XS

#62 Add support to whitelist urls for markdown linting.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#64 Ensure GOBIN is set to an absolute path as this is required in istio/…
  files/Makefile
Labels: cla: yes, size/XS

#65 Common file fixes.
  files/Makefile
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#67 Update golangci-lint to v1.18.0
  files/Makefile
  files/common/config/.golangci.yml
  files/common/scripts/lint_go.sh
Labels: cla: yes, size/S

#68 Update image
  files/Makefile
Labels: cla: yes, size/XS

#70 Backport gobuild changes
  files/common/scripts/gobuild.sh
Labels: cla: yes, size/XS

#66 support use of alternate container tool
  files/Makefile
Labels: cla: yes, size/S

#71 Update container image.
  files/Makefile
  files/common/scripts/gobuild.sh
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/S

#72 Set timezone data in a platform independent way
  files/Makefile
Labels: cla: yes, size/S

#73 Delete ruby protocol buffers
  common-protos/google/protobuf/compiler/ruby/ruby_generated_code.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_code_proto2.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit.proto
  get_protos.sh
Labels: cla: yes, size/L

#74 Remove unneeded variables
  files/Makefile
Labels: cla: yes, size/XS

#75 Sync with latest get_workspace_status.sh from istio/istio.
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/S

#76 Begin rollout of updated build-tools container
  files/Makefile
Labels: cla: yes, size/XS

#77 Adapt to latest build tools container.
  files/Makefile
Labels: cla: yes, size/M

#78 verify go version before build
  files/common/scripts/gobuild.sh
Labels: cla: yes, size/XS

#79 Report the type of build environment in use.
  files/Makefile
Labels: cla: yes, size/XS

#80 Update to latest container image.
  files/Makefile
Labels: cla: yes, size/XS

#81 fix python linter.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#82 gobuild: Do not pass -trimpath to go build on debug builds
  files/common/scripts/gobuild.sh
Labels: cla: yes, size/XS

#83 Add .gitignore
  .gitignore
Labels: cla: yes, size/XS

#85 Stop passing BUILD_WITH_CONTAINER into the container in order to avoid recursion issues.
  files/Makefile
Labels: cla: yes, size/XS

#86 Update to the official 1.3 SHA of gogo.
  get_protos.sh
Labels: cla: yes, size/XS

#87 Add support for license linting
  files/common/Makefile.common.mk
  files/common/config/license-lint.yml
Labels: cla: yes, size/M

#88 Expand license whitelist to cover istio/istio
  files/common/Makefile.common.mk
  files/common/config/license-lint.yml
Labels: cla: yes, size/M
