Repository istio/common-files, pull requests merged in 2019-07, with the labels that each got.

#13 Submit a Dockerfile image linter
  files/scripts/check_dockerfiles.sh
Labels: size/M

#14 Fix istio/lint bad substitution error
  files/scripts/check_dockerfiles.sh
Labels: size/XS

#15 Disable mergify, now using Tide.
  .mergify.yml
  README.md
Labels: cla: yes, size/S

#16 Update go-bindata
  files/scripts/run_gobindata.sh
Labels: cla: yes, size/XS

#17 Keep script linter happy.
  files/scripts/run_gobindata.sh
Labels: cla: yes, size/XS
