Repository istio/common-files, pull requests merged in 2019-11, with the labels that each got.

#127 Update container image
  files/Makefile
Labels: cla: yes, size/XS

#128 Update release 1.4 image
  files/Makefile
Labels: cla: yes, size/XS

#129 [release-1.4] Fix TARGET_OUT to match istio/istio
  files/Makefile
Labels: cla: yes, size/XS

#130 Update the img id with the latest build-tools img
  files/Makefile
Labels: cla: yes, size/XS

#131 Updating prow image to ubuntu bionic
  files/Makefile
Labels: cla: yes, size/XS

#132 updating prow image
  files/Makefile
Labels: cla: yes, size/XS

#133 Only pass environment variables that are set
  files/Makefile
Labels: cherrypick/release-1.4, cla: yes, size/S

#134 Only pass environment variables that are set (#133)
  files/Makefile
Labels: cla: yes, size/S

#135 Bump builder image
  files/Makefile
Labels: cla: yes, size/XS

#136 updating prow image (again)
  files/Makefile
Labels: cla: yes, size/XS

#137 uptick build image
  files/Makefile
Labels: cla: yes, size/XS

#138 update container image
  files/Makefile
Labels: cla: yes, size/XS

#139 updating prow image (again)
  files/Makefile
Labels: cla: yes, size/XS

#141 update container image
  files/Makefile
Labels: cla: yes, size/XS

#140 Export GOBIN so that it is readable from Makefile.core.mk
  files/Makefile
Labels: cherrypick/release-1.4, cla: yes, size/XS

#143 Export GOBIN so that it is readable from Makefile.core.mk
  files/Makefile
Labels: cla: yes, size/XS

#142 Fix common-protos copy
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#144 Remove a few modules from the whitelist since we don't need 'em anymore.
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#145 Add option to use proxy builder image
  files/Makefile
Labels: cla: yes, size/XS

#146 update container image 1.4
  files/Makefile
Labels: cla: yes, size/XS

#147 Add `git diff` to gen-check
  files/common/scripts/check_clean_repo.sh
Labels: cla: yes, size/XS

#148 Update build tools
  files/Makefile
Labels: cla: yes, size/XS

#150 Set default hub
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/XS

#151 Fix recursive cp
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#153 Add aarch64 support in files/Makefile
  files/Makefile
Labels: cla: yes, ok-to-test, size/XS

#154 Fix default hub
  files/common/scripts/report_build_info.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#155 [1.4] Fix default hub
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/XS

#156 Update build tools
  files/Makefile
Labels: cla: yes, size/XS

#158 Cherrypick of #123, #142, and #151 from master
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#160 Update common-files to master-2019-11-26T07-29-27
  files/Makefile
Labels: cla: yes, size/XS
