Repository istio/common-files, pull requests merged in 2019-08, with the labels that each got.

#18 Update for container-based builds.
  files/Makefile
  files/Makefile.common.mk
Labels: cla: yes, size/M

#19 Add default target.
  files/Makefile
Labels: cla: yes, size/XS

#20 Updates from operator into commmon-files
  files/Makefile
Labels: cla: yes, size/M

#22 Updates from operator into commmon-files
  files/Makefile
Labels: cla: yes, size/M

#23 Add Steve to CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS

#24 Update GOBIN to work with containers and Mac
  files/Makefile
Labels: cla: yes, size/XS

#25 Fix the generated .commonfiles.sha
  files/Makefile.common.mk
Labels: cla: yes, size/XS

#26 Remove trailing spaces
  files/SUPPORT.md
Labels: cla: yes, size/XS

#27 Add --no-print-directory to Makefile
  files/Makefile
Labels: cla: yes, size/XS

#28 Update with latest build image
  files/Makefile
Labels: cla: yes, size/XS

#29 Add support for Makefile.overrides.mk and CONTAINER_OPTIONS.
  files/Makefile
Labels: cla: yes, size/XS

#31 Ensure Makefile.overrides.mk exists, to avoid warnings from make on macOS
  files/Makefile.common.mk
Labels: cla: yes, size/XS

#30 Update Makefile to latest container image
  files/Makefile
Labels: cla: yes, size/XS

#32 Update buildtools to latest
  files/Makefile
Labels: cla: yes, size/XS

#33 Update container image.
  files/Makefile
  files/scripts/run_gobindata.sh
Labels: cla: yes, size/XS

#34 Remove date range from copyright notice.
  LICENSE
Labels: cla: yes, size/XS

#36 Add missing colon.
  files/Makefile.common.mk
Labels: cla: yes, size/XS

#37 Update container version.
  files/Makefile
Labels: cla: yes, size/XS

#38 Update container image again.
  files/Makefile
Labels: cla: yes, size/XS

#39 Update common files
  files/Makefile
  files/Makefile.common.mk
  files/scripts/lint_copyright_banner.sh
Labels: cla: yes, size/M

#40 Common files improvements
  files/Makefile
  files/Makefile.common.mk
  files/common/Makefile.common.mk
  files/common/config/.golangci.yml
  files/common/config/.hadolint.yml
  files/common/config/.yamllint.yml
  files/common/scripts/gobuild.sh
  files/common/scripts/lint_copyright_banner.sh
  files/common/scripts/report_build_info.sh
  files/scripts/check_dockerfiles.sh
  files/scripts/lint_copyright_banner.sh
  files/scripts/run_gobindata.sh
  files/scripts/run_gofmt.sh
Labels: cla: yes, size/L

#41 More common files updates.
  files/Makefile
  files/common/Makefile.common.mk
  files/common/scripts/gobuild.sh
Labels: cla: yes, size/S

#45 Fix problem with PR#42 that introduced protos
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#44 Linting tweaks.
  files/common/Makefile.common.mk
  files/common/config/mdl.rb
  files/common/config/sass-lint.yml
  files/common/config/tslint.json
Labels: cla: yes, size/L

#46 Cleanup.
  files/common/Makefile.common.mk
  files/common/config/mdl.rb
Labels: cla: yes, size/XS

#47 Rework report-build-info
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/S

#48 Add missing protos for gogo-genproto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/common/v1/common.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/metrics/v1/metrics_service.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/trace/v1/trace_service.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/metrics/v1/metrics.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/resource/v1/resource.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/stats/v1/stats.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/trace/v1/trace.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/trace/v1/trace_config.proto
  common-protos/github.com/prometheus/client_model/metrics.proto
  common-protos/k8s.io/api/admissionregistration/v1/generated.proto
  common-protos/k8s.io/api/admissionregistration/v1beta1/generated.proto
  common-protos/k8s.io/api/apps/v1/generated.proto
  common-protos/k8s.io/api/apps/v1beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta2/generated.proto
  common-protos/k8s.io/api/batch/v1/generated.proto
  common-protos/k8s.io/api/batch/v1beta1/generated.proto
  common-protos/k8s.io/api/batch/v2alpha1/generated.proto
  common-protos/k8s.io/api/coordination/v1/generated.proto
  common-protos/k8s.io/api/coordination/v1beta1/generated.proto
  common-protos/k8s.io/api/core/v1/generated.proto
  common-protos/k8s.io/api/events/v1beta1/generated.proto
  common-protos/k8s.io/api/networking/v1beta1/generated.proto
  common-protos/k8s.io/api/node/v1alpha1/generated.proto
  common-protos/k8s.io/api/node/v1beta1/generated.proto
  common-protos/k8s.io/api/policy/v1beta1/generated.proto
  common-protos/k8s.io/api/scheduling/v1/generated.proto
  common-protos/k8s.io/api/scheduling/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1/generated.proto
  common-protos/k8s.io/api/storage/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1beta1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/api/resource/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto
  get_protos.sh
Labels: cla: yes, size/XXL

#49 Update to latest image.
  files/Makefile
  files/common/Makefile.common.mk
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/XS

#50 Exclude common-protos from linting.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS
