Repository istio/common-files, pull requests merged in 2019-10, with the labels that each got.

#89 Set the docker group ID in the make operation
  files/Makefile
Labels: cla: yes, size/XS

#92 Common file updates
  files/Makefile
  files/common/Makefile.common.mk
  files/common/scripts/check_clean_repo.sh
Labels: cla: yes, size/S

#91 Pass BUILD_WITH_CONTAINER to the child containers
  files/Makefile
Labels: cla: yes, size/XS

#93 container-tools: 2019-10-02T16-55-19
  files/Makefile
Labels: cla: yes, size/XS

#95 Use buildtools: 2019-10-03T17-21-57
  files/Makefile
Labels: cla: yes, size/XS

#96 adding required dependency to whitelist
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#98 Use --net=host to permit dind to work properly
  files/Makefile
Labels: cla: yes, size/XS

#99 Updates to accommodate the latest container changes.
  files/Makefile
Labels: cla: yes, size/S

#100 Set TARGET_OUT within container properly
  files/Makefile
Labels: cla: yes, size/XS

#101 Update for latest container image.
  files/Makefile
Labels: cla: yes, size/XS

#102 update to latest container image
  files/Makefile
Labels: cla: yes, size/XS

#103 Add make bash completion instructions to readme
  README.md
Labels: cla: yes, size/S

#105 Remove --net=host since that breaks web serving in the istio.io repo.
  files/Makefile
Labels: cla: yes, size/XS

#106 Pass $HUB and $TAG to the docker container
  files/Makefile
Labels: cla: yes, size/XS

#108 Release 1.4 codeowners, branch updates
  CODEOWNERS
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#110 Fix TARGET_OUT to match istio/istio
  files/Makefile
Labels: cla: yes, size/XS

#109 Makefile updates.
  files/Makefile
  files/common/Makefile.common.mk
Labels: cla: yes, size/M

#111 Rationalize docker config for docker.push
  files/Makefile
Labels: cla: yes, size/S

#113 Fix a recent update to common files that breaks updates
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#114 Add support for license mirroring.
  files/common/Makefile.common.mk
Labels: cherrypick/release-1.4, cla: yes, size/XS

#115 Update to latest container.
  files/Makefile
Labels: cla: yes, size/XS

#112 Add HUB and ISTIO_VERSION variables for build istio/operator
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/XS

#117 Common file updates.
  files/Makefile
  files/common/Makefile.common.mk
  files/common/scripts/check_clean_repo.sh
Labels: cla: yes, size/XS

#118 Update golangci-lint version to match what's in the container.
  files/common/config/.golangci.yml
  files/common/scripts/lint_go.sh
Labels: cla: yes, size/S

#116 [release 1.4] add docker hub build variable for operator
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/XS

#119 Avoid linting the new licenses directory.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#120 Delete the licenses directory before populating it so superfluous licenses disappear.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#121 Use latest container image.
  files/Makefile
Labels: cla: yes, size/XS

#122 Port a few common file changes from master.
  files/Makefile
  files/common/Makefile.common.mk
  files/common/scripts/check_clean_repo.sh
Labels: cla: yes, size/M

#123 Fix the update-common targets to work on a Mac.
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#125 Update container image
  files/Makefile
Labels: cla: yes, size/XS

#126 Update container image again
  files/Makefile
Labels: cla: yes, size/XS
