Repository istio/common-files, pull requests merged in 2019-12, with the labels that each got.

#161 Update container to the latest
  files/Makefile
Labels: cla: yes, size/XS

#163 Update image and linter config
  files/Makefile
  files/common/config/.golangci.yml
Labels: cla: yes, size/XS

#164 Split markdown linter to isolate link check
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#165 Clean extra tab
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#166 Update container image
  files/Makefile
Labels: cla: yes, size/XS

#167 Add istio api extensions to common-files
  common-protos/istio.io/extensions/field_rules.proto
  get_protos.sh
  protos/istio.io/extensions/field_rules.proto
Labels: cla: yes, size/L

#168 Add conditional host mount of $HOME/.kube
  files/Makefile
Labels: cla: yes, size/S

#170 Add a new module to license lint config
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#171 Manual update to master-2019-12-15T16-17-48
  files/Makefile
Labels: cla: yes, size/XS

#169 Add a TARGET_OUT_LINUX environment variable
  files/Makefile
Labels: cla: yes, size/XS
