Repository istio/common-files, pull requests merged in 2020-09, with the labels that each got.

#305 Fix use of DEBUG=1 on Make
  files/common/scripts/gobuild.sh
Labels: cla: yes, size/XS

#306 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#307 Create passwd entry and group entry on startup of container
  files/common/scripts/run.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#308 fix container_kubeconfig path - should have been /config instead of /home
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/XS

#310 Deduplicate kind cluster setup and refactor cluster topology configuration into a file to define arbitrary topologies
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, ok-to-test, size/L

#311 KUBECONFIGS should be exported so that it can be used downstream
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, ok-to-test, size/XS

#312 Kind provisioner script fixup
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, ok-to-test, size/M

#314 fix documentation and formatting
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, ok-to-test, size/S

#313 Update build tools for kind v0.9.0
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#315 remove unnecessary docker network create
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#316 Run Kubernetes 1.19 in CI
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#317 Allow override of DOCKER_GID in setup_env.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#318 Update build image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#320 Fix yamllint and license rule
  files/common/Makefile.common.mk
  files/common/config/.yamllint.yml
Labels: cla: yes, size/XS

#321 Disable yamllint octal-values
  files/common/config/.yamllint.yml
Labels: cla: yes, size/XS
