Repository istio/common-files, pull requests merged in 2020-08, with the labels that each got.

#290 Ability to ignore a dirty tree when reporting tree status
  files/common/scripts/report_build_info.sh
Labels: cherrypick/release-1.7, cla: yes, size/XS

#291 [release-1.7] Ability to ignore a dirty tree when reporting tree status
  files/common/scripts/report_build_info.sh
Labels: cla: yes, release-notes-none, size/XS

#292 Update to master-2020-08-03T16-23-11 for golangci-lint 1.30
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#293 Update image - fix shellcheck error
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#294 Fix liniting errors
  files/common/scripts/gobuild.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#297 Bump image version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#296 [release-1.7] Bump image version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#298 [release-1.7] Fix liniting errors
  files/common/scripts/gobuild.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#295 Move formatting to golangci-lint+gci
  files/common/Makefile.common.mk
  files/common/config/.golangci-format.yml
  files/common/scripts/format_go.sh
Labels: cla: yes, size/M

#299 Bump builder image to golang 1.15
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#300 Use the variable VERSION, if it is defined
  files/common/scripts/report_build_info.sh
Labels: cla: yes, size/XS

#301 Change image version
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/XS
