Repository istio/common-files, pull requests merged in 2020-04, with the labels that each got.

#223 Update to call local make
  files/Makefile
Labels: cla: yes, size/XS

#224 Update build image
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/XS

#225 Update license linter
  files/common/config/license-lint.yml
Labels: cla: yes, size/S

#226 Dont pass env vars CC and CXX to build container
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#227 Update container
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#228 allow overriding platform and architecture values
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/S

#229 Change if to correct for it being non-zero length
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#230 Update build image to use Golang 1.14.2
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#231 Update to build image supporting k8s code gen 1.18.1
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#232 Add check-no-modify target to prevent some files from being modified
  files/common/Makefile.common.mk
  files/common/scripts/check_no_modify.sh
  files/common/scripts/nomodify.md5
Labels: cla: yes, size/S

#233 Fix license whitelist for helm v3
  files/common/config/license-lint.yml
Labels: cla: yes, size/S

#234 build-tools: use to latest master tag
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#235 Revert "Add check-no-modify target to prevent some files from being modified in the repo (#232)"
  files/common/Makefile.common.mk
  files/common/scripts/check_no_modify.sh
  files/common/scripts/nomodify.md5
Labels: cla: yes, size/S

#236 Updated for release-1.6
  CODEOWNERS
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#237 Set up the conditional mounts correctly
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/S

#238 Bump build-tools
  files/common/config/license-lint.yml
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#239 Update license files for Redigo
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS
