Repository istio/common-files, pull requests merged in 2020-11, with the labels that each got.

#340 Bump build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#341 [release-1.8] Update build image to fix helm
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#342 Stop skipping linter in integration test
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
Labels: cla: yes, size/XS

#343 Install Metallb for single cluster too
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#344 Install metallb for multicluster in single cluster install only
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S

#345 fix matllb install
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S

#346 Allow overriding mount source and dest
  files/common/scripts/run.sh
Labels: cla: yes, size/XS

#347 [release-1.8] Update 1.8 to buildimage with golang 1.15.5 (security update)
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#349 [release-1.7] Update to use new build image with Golang 1.14.12
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#348 Update to buildimage with golang 1.15.5 (security update)
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#350 [release-1.6] Update to use build image containing Golang 1.4.12 (security fix)
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#352 [release-1.8] Install Metallb for single cluster too
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, release-notes-none, size/XS

#354 default kind image
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#353 [release-1.8] Install metallb for multicluster in single cluster install only
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, release-notes-none, size/S

#326 Add support on s390x
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/XS

#355 Bump build-tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS
