Repository istio/common-files, pull requests merged in 2020-07, with the labels that each got.

#268 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#270 Bump build image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#271 Better handle vendored trees
  files/common/Makefile.common.mk
Labels: cla: yes, size/S

#272 [release-1.6] Better handle vendored trees
  files/common/Makefile.common.mk
Labels: cla: yes, size/S

#274 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#275 set common make shell to bash
  files/common/Makefile.common.mk
Labels: cla: yes, ok-to-test, size/XS

#277 Revert "set common make shell to bash"
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#278 Bump build-tools image tag to master-2020-07-13T16-10-49
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#279 Replace deprecated `whitelisted_modules`
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#273 Change caching to `cached` in support of new file synchronization
  files/common/scripts/run.sh
Labels: cla: yes, size/XS

#276 Allow setting MARKDOWN_LINT_ALLOWLIST instead of _WHITELIST
  files/common/Makefile.common.mk
Labels: cla: yes, ok-to-test, size/XS

#280 Clean up MARKDOWN_LINT_WHITELIST
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#281 Update build image - Golang 1.14.5
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#282 Bump Build image - Fix golangci-lint fault - Update golangci-lint, upx
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#285 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/XS

#286 Update files for release-1.7
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#284 Use /home/.cache as a volume mount
  files/common/scripts/run.sh
Labels: cla: yes, release-notes-none, size/XS

#287 update image version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#288 New image version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#289 Fix KUBECONFIG when running script directly
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS
