Repository istio/common-files, pull requests merged in 2020-03, with the labels that each got.

#200 Fix for yaml-lint
  files/Makefile
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#202 Update build tools
  files/Makefile
Labels: cla: yes, size/XS

#172 Add docker run script
  files/Makefile
  files/common/scripts/run.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/L

#204 Revert "Add docker run script"
  files/Makefile
  files/common/scripts/run.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/L

#205 configurable image name (IMAGE_NAME) via environment
  files/Makefile
Labels: cla: yes, size/XS

#206 whitelist modules for k8s.io/test-infra dep
  files/common/config/license-lint.yml
Labels: cla: yes, size/S

#207 Attempt 2 at docker run script
  files/Makefile
  files/common/scripts/run.sh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/L

#208 PWD is not always set in CI
  files/Makefile
Labels: cla: yes, size/XS

#209 Fix make for CI
  files/Makefile
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#211 Document a confusing export usage
  files/Makefile
Labels: cla: yes, size/XS

#212 Fix Makefile.overrides.mk
  files/Makefile
Labels: cla: yes, size/XS

#213 whitelist modules for k8s.io/test-infra dep
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#215 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#216 Update build tools image version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#217 Remove functions from the list of exported variables
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#218 Fix `/bin/bash: @find: command not found` for lint-yaml
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#219 Update build tools image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#221 Update build image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#220 Update release-1.5 build image
  files/Makefile
Labels: cla: yes, size/XS

#222 Fix recursive make
  files/Makefile
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/S
