Repository istio/common-files, pull requests merged in 2020-06, with the labels that each got.

#257 Update common files to latest
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#255 Make signals work during build and test operations
  files/common/scripts/run.sh
Labels: cla: yes, size/XS

#259 license-lint: add a few forks
  files/common/config/license-lint.yml
Labels: cla: yes, ok-to-test, size/XS

#258 Add help target
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#254 All of our dockerfiles ignore DL3008
  files/common/config/.hadolint.yml
Labels: cla: yes, size/XS

#256 Follow K8s loading pattern in makefiles
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/M

#260 Add fix-copyright-banner
  files/common/Makefile.common.mk
  files/common/scripts/copyright-banner-go.txt
  files/common/scripts/fix_copyright_banner.sh
Labels: cla: yes, size/M

#262 Bump build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#261 Only mount/add kubeconfig in build container if it exists
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/S

#263 Bump build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#264 Fix staticchek on proto
  files/common/config/.golangci.yml
  files/common/scripts/fix_copyright_banner.sh
Labels: cla: yes, size/XS

#265 Update .golangci.yml
  files/common/config/.golangci.yml
Labels: cla: yes, size/XS

#266 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS
