Repository istio/common-files, pull requests merged in 2020-10, with the labels that each got.

#323 Update lint-yaml to not fail when no files containing {{ are found
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#322 [release-1.6] Update build image to one using Golang 1.14.9
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#324 Bump base image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#309 Trim and document license allowlist
  files/common/config/license-lint.yml
Labels: cla: yes, size/L

#325 Bump build-tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#328 Fix .netrc
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#329 Update build image to fix gh
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#330 use GCR images for CI
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S

#331 [release-1.8] Automated branching step 4
  CODEOWNERS
Labels: cla: yes, release-notes-none, size/XS

#332 [release-1.8] Automated branching step 5
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#333 Use build image with gen-release-notes
  files/common/scripts/setup_env.sh
Labels: cla: yes, do-not-merge, size/XS

#334 Include templates in build tools image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#335 Update build tools version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#337 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#338 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#339 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS
