Repository istio/common-files, pull requests merged in 2021-05, with the labels that each got.

#410 Update base
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#411 files/Makefile: fix shell target to be phony
  files/Makefile
Labels: cla: yes, ok-to-test, size/XS

#409 Update base
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#412 Update build image: gh 1.9.2, golang 1.16.4, remove gobin
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#415 Allowlist a specific import order
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
Labels: cherrypick/release-1.8, cla: yes, size/XS

#417 Update build-tools: AWESOMEBOT, FPM, HTMLPROOFER, LICENSEE, MDL, kind, protoc-gen-validate
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#421 Bump docker
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#422 add exportloopref linter
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
Labels: cla: yes, size/XS

#423 Add docker debug
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#426 Fix docker image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#425 Increase wait for kind
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S

#427 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#429 Update build image - kind 0.11.1
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS
