Repository istio/common-files, pull requests merged in 2021-11, with the labels that each got.

#482 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#484 Update for hadolint - Ignore Multiple consecutive RUN instructions.
  files/common/config/.hadolint.yml
Labels: size/XS, cla: yes

#487 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#488 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#489 Enable metallb for IPv6
  files/common/scripts/kind_provisioner.sh
Labels: size/M, cla: yes

#490 Remove useless shell script in makefile
  files/Makefile
Labels: size/XS, cla: yes

#492 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#493 Bump build image
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#494 Remove dead code
  files/common/scripts/kind_provisioner.sh
Labels: size/S, cla: yes

#491 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#495 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none
