Repository istio/common-files, pull requests merged in 2021-12, with the labels that each got.

#496 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#498 Add an end space to CONDITIONAL_HOST_MOUNTS.
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#497 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#499 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#501 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#502 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#500 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#503 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#504 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
