Repository istio/common-files, pull requests merged in 2021-01, with the labels that each got.

#359 Adding ppc64le architecture support
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/XS

#360 Cleanup unused protos
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/common/v1/common.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/metrics/v1/metrics_service.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/agent/trace/v1/trace_service.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/metrics/v1/metrics.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/resource/v1/resource.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/stats/v1/stats.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/trace/v1/trace.proto
  common-protos/github.com/census-instrumentation/opencensus-proto/src/opencensus/proto/trace/v1/trace_config.proto
  common-protos/github.com/envoyproxy/protoc-gen-validate/gogoproto/gogo.proto
  common-protos/github.com/envoyproxy/protoc-gen-validate/validate/validate.proto
  common-protos/github.com/prometheus/client_model/metrics.proto
  get_protos.sh
Labels: cla: yes, size/XXL

#351 automatically detect whether to run `docker run -it` or just `docker run`
  files/common/scripts/run.sh
Labels: cla: yes, size/XS

#361 Update build-tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#363 Update build-tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#364 Bump tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#365 Update gogo protobuf to v1.3.2
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/compiler/plugin.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/duration.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/struct.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/timestamp.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/type.proto
  get_protos.sh
Labels: cla: yes, size/L

#366 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#367 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/XS

#368 Update build tools for 1.9
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#369 Set release managers as CODEOWNERS for release-1.9 (#367)
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS

#370 Update image for new docs protoc plugin
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#371 store metallb manifest in repo
  files/common/scripts/kind_provisioner.sh
  files/common/scripts/metallb.yaml
Labels: cla: yes, do-not-merge/work-in-progress, size/L

#372 support cluster factory in kind_provisioner
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S

#373 Remove [] on CLUSTER_NETWORK_ID
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#374 Hide generated json files
  files/.gitattributes
Labels: cla: yes, size/XS

#375 fix topology file reader
  files/common/scripts/kind_provisioner.sh
Labels: cla: yes, size/XS

#376 [release-1.9] update kind provisioner
  files/common/scripts/kind_provisioner.sh
  files/common/scripts/metallb.yaml
Labels: cla: yes, size/L

#377 [release-1.9] Update build-image - pins to older kuernetes test-infra
  files/common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#378 [release-1.8] improve cluster config file reader
  files/common/scripts/kind_provisioner.sh
  files/common/scripts/metallb.yaml
Labels: cla: yes, size/L

#379 Bump image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#380 [release-1.7] Update build-tools to latest version
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#381 Update build-tools image to Golang 1.16rc1
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#382 Negate Golang 1.16 go mod download affecting go.sum
  files/common/Makefile.common.mk
Labels: cla: yes, size/XS
