Repository istio/common-files, pull requests merged in 2021-08, with the labels that each got.

#459 Handle LOCAL_ARCH on Apple M1
  files/common/scripts/setup_env.sh
Labels: cla: yes, ok-to-test, size/XS

#460 Update build-tools image: Golang 1.16.7
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#461 Bump build image
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#462 Update build tools for release 1.9
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#463 [release-1.10] Automated branching step 4 (#395)
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes
