Repository istio/common-files, pull requests merged in 2021-09, with the labels that each got.

#465 script to build new build-tools images and update to use them
  bin/create-buildtools-and-update.sh
  bin/update-build-image.sh
Labels: size/M, cla: yes

#466 Update build-tools: gcloud SDK, gh
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#468 Update build-tools image: update gh
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#470 Update build-tools: update golang, shellcheck, containerd, docs tooling
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#467 Update build-tools image: update gh
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#471 Use AUTOMATOR_REPO_DIR if set to call script (implies running pipeline)
  bin/create-buildtools-and-update.sh
Labels: size/S, cla: yes

#472 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes, release-notes-none

#469 [release-1.11] Update build-tools image: update gh, Golang
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes

#473 [release-1.10] Update build-tools image: Golang 1.16.8
  files/common/scripts/setup_env.sh
Labels: size/XS, cla: yes
