Repository istio/common-files, pull requests merged in 2021-07, with the labels that each got.

#441 Update build tools
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#442 [release-1.10] Update tools to include trivy
  files/common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#443 Update build-tools, updating gh, adding buf back
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#444 [release-1.9] Update build image: Add Trivy
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#445 Add runc in license-lint.yml
  files/common/config/license-lint.yml
Labels: cla: yes, ok-to-test, size/XS

#446 Update to Golang 1.16.6
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#447 Update build-tools: revert buf
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#448 [release-1.9] update build-tools: golang security update
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#452 Updte build image: buf and CUE link
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#449 [release-1.10] Update build tools: golang security update
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#453 Set correct values for 1.11 branch
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#454 [release-1.11] Automated branching step 4
  CODEOWNERS
Labels: cla: yes, release-notes-none, size/XS

#455 Allowlist github.com/felixge/fgprof to update k8s.io/test-infra dependency for istio.io/test-infra repo
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#456 Allowlist github.com/google/pprof to update k8s.io/test-infra dependency for istio.io/test-infra repo
  files/common/config/license-lint.yml
Labels: cla: yes, size/XS

#457 Update buildImage: gcloud, kubetest2, DNS
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#458 Bump build image
  files/common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#440 Drop grpcgen hack from linter config
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
Labels: cla: yes, size/XS
