Repository istio/common-files, pull requests merged in 2022-10, with the labels that each got.

#678 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#677 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#679 Automator: update build-tools image@release-1.15 in istio/common-files@release-1.15
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#676 Updates noted while converting istio/community to use common-files
  files/LICENSE
  files/common/Makefile.common.mk
Labels: size/XS

#680 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#681 Add depguard
  files/common/config/.golangci.yml
Labels: size/XS

#684 Update metallb to 0.12.1
  files/common/scripts/metallb.yaml
Labels: size/L

#685 Revert "Update metallb to 0.12.1"
  files/common/scripts/metallb.yaml
Labels: size/L

#682 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#686 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#688 [release-1.16] Automated branching step 4
  CODEOWNERS
Labels: size/XS, release-notes-none

#687 Add build arch to build info
  files/common/scripts/report_build_info.sh
Labels: size/XS

#690 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#689 Add rust cache volume mounts
  files/common/scripts/run.sh
Labels: size/XS

#692 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#693 Fix os and arch not reported
  files/common/scripts/gobuild.sh
Labels: size/XS

#694 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#696 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: do-not-merge, size/XS, release-notes-none

#695 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
