Repository istio/common-files, pull requests merged in 2022-02, with the labels that each got.

#525 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#526 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#528 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#527 Automator: update build-tools image@release-1.13 in istio/common-files@release-1.13
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#530 Automator: update build-tools image@release-1.13 in istio/common-files@release-1.13
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#531 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#533 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#534 Bump build image
  files/common/scripts/setup_env.sh
Labels: size/XS

#536 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#535 Backport changes from istio/istio for kind retries
  files/common/scripts/kind_provisioner.sh
Labels: size/M

#537 We trust in quay.io registry
  files/common/config/.hadolint.yml
Labels: size/XS

#538 [release-1.12] We trust in quay.io registry
  files/common/config/.hadolint.yml
Labels: size/XS, release-notes-none

#539 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
