Repository istio/common-files, pull requests merged in 2022-07, with the labels that each got.

#625 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#626 fix kind provisioner cidr gen
  files/common/scripts/kind_provisioner.sh
Labels: size/S

#627 fix kind provisioner cidr gen
  files/common/scripts/kind_provisioner.sh
Labels: size/S

#628 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#629 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#631 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#634 [release-1.14] Update default kind node as 1.19.1 fails with latest kind 0.14.0
  files/common/scripts/kind_provisioner.sh
Labels: size/XS, release-notes-none

#635 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#633 Update protobuf exception
  files/common/config/.golangci.yml
Labels: size/XS

#636 Automator: update build-tools image@release-1.13 in istio/common-files@release-1.13
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#637 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#632 add lint-gci
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
Labels: size/S

#639 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#640 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#641 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#642 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
