Repository istio/common-files, pull requests merged in 2022-04, with the labels that each got.

#571 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#572 Fix `make build` in istio/istio using wrong Golang cache directory.
  files/common/scripts/setup_env.sh
Labels: size/XS

#573 Fix make build in istio/istio
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#574 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#576 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#575 replace golint with revive
  files/common/config/.golangci.yml
Labels: size/M

#577 Workaround kind 1.24 issue
  files/common/scripts/kind_provisioner.sh
Labels: size/XS

#578 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#560 Automator: update build-tools image@release-1.13 in istio/common-files@release-1.13
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#579 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#580 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#582 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#584 [release-1.14] Automated branching step 4
  CODEOWNERS
Labels: size/XS, release-notes-none

#586 [release-1.14] Automated branching step 5
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#587 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#590 Remove trap to prevent early cluster termination
  files/common/scripts/kind_provisioner.sh
Labels: size/M

#589 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#591 [release-1.14] Remove trap to prevent early cluster termination
  files/common/scripts/kind_provisioner.sh
Labels: size/M, release-notes-none

#588 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#593 Remove update-common-protos
  files/common/Makefile.common.mk
  get_protos.sh
Labels: size/S

#592 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
