Repository istio/common-files, pull requests merged in 2022-11, with the labels that each got.

#697 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#698 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#700 Automator: update build-tools image@release-1.15 in istio/common-files@release-1.15
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#701 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#699 Automator: update build-tools image@release-1.14 in istio/common-files@release-1.14
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#702 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#703 fix: excludes Ruby env vars
  files/common/scripts/setup_env.sh
Labels: size/XS, ok-to-test

#704 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#705 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#706 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#708 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#707 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#710 Copy change from istio/istio/41872 to prevent override
  files/common/config/.golangci.yml
Labels: size/XS

#711 [release-1.16] Copy change from istio/istio/41872 to prevent override
  files/common/config/.golangci.yml
Labels: size/XS, release-notes-none

#709 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#712 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#713 Update default k8s version to a supported version
  files/common/scripts/kind_provisioner.sh
Labels: size/XS

#714 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#715 Add gosec checkers
  files/common/config/.golangci.yml
Labels: size/XS, ok-to-test

#716 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#719 chore: clean proto related targets
  files/common/Makefile.common.mk
Labels: size/XS

#720 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#717 chore: check and fix copyright banner in rust codes
  files/common/Makefile.common.mk
  files/common/scripts/fix_copyright_banner.sh
Labels: size/XS

#721 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#718 chore: fix run as root issue
  files/common/scripts/run.sh
Labels: size/XS

#722 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
