Repository istio/common-files, pull requests merged in 2022-03, with the labels that each got.

#542 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#543 Add more retry to kind creation
  files/common/scripts/kind_provisioner.sh
Labels: size/XS

#544 Update protos
  common-protos/k8s.io/api/admission/v1/generated.proto
  common-protos/k8s.io/api/admission/v1beta1/generated.proto
  common-protos/k8s.io/api/admissionregistration/v1/generated.proto
  common-protos/k8s.io/api/admissionregistration/v1beta1/generated.proto
  common-protos/k8s.io/api/apiserverinternal/v1alpha1/generated.proto
  common-protos/k8s.io/api/apps/v1/generated.proto
  common-protos/k8s.io/api/apps/v1beta1/generated.proto
  common-protos/k8s.io/api/apps/v1beta2/generated.proto
  common-protos/k8s.io/api/auditregistration/v1alpha1/generated.proto
  common-protos/k8s.io/api/authentication/v1/generated.proto
  common-protos/k8s.io/api/authentication/v1beta1/generated.proto
  common-protos/k8s.io/api/authorization/v1/generated.proto
  common-protos/k8s.io/api/authorization/v1beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta2/generated.proto
  common-protos/k8s.io/api/batch/v1/generated.proto
  common-protos/k8s.io/api/batch/v1beta1/generated.proto
  common-protos/k8s.io/api/batch/v2alpha1/generated.proto
  common-protos/k8s.io/api/certificates/v1/generated.proto
  common-protos/k8s.io/api/certificates/v1beta1/generated.proto
  common-protos/k8s.io/api/coordination/v1/generated.proto
  common-protos/k8s.io/api/coordination/v1beta1/generated.proto
  common-protos/k8s.io/api/core/v1/generated.proto
  common-protos/k8s.io/api/discovery/v1/generated.proto
  common-protos/k8s.io/api/discovery/v1beta1/generated.proto
  common-protos/k8s.io/api/events/v1/generated.proto
  common-protos/k8s.io/api/events/v1beta1/generated.proto
  common-protos/k8s.io/api/extensions/v1beta1/generated.proto
  common-protos/k8s.io/api/flowcontrol/v1alpha1/generated.proto
  common-protos/k8s.io/api/flowcontrol/v1beta1/generated.proto
  common-protos/k8s.io/api/flowcontrol/v1beta2/generated.proto
  common-protos/k8s.io/api/imagepolicy/v1alpha1/generated.proto
  common-protos/k8s.io/api/networking/v1/generated.proto
  common-protos/k8s.io/api/networking/v1beta1/generated.proto
  common-protos/k8s.io/api/node/v1/generated.proto
  common-protos/k8s.io/api/node/v1alpha1/generated.proto
  common-protos/k8s.io/api/node/v1beta1/generated.proto
  common-protos/k8s.io/api/policy/v1/generated.proto
  common-protos/k8s.io/api/policy/v1beta1/generated.proto
  common-protos/k8s.io/api/rbac/v1/generated.proto
  common-protos/k8s.io/api/rbac/v1alpha1/generated.proto
  common-protos/k8s.io/api/rbac/v1beta1/generated.proto
  common-protos/k8s.io/api/scheduling/v1/generated.proto
  common-protos/k8s.io/api/scheduling/v1alpha1/generated.proto
  common-protos/k8s.io/api/scheduling/v1beta1/generated.proto
  common-protos/k8s.io/api/settings/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1/generated.proto
  common-protos/k8s.io/api/storage/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1beta1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/api/resource/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/runtime/generated.proto
  common-protos/k8s.io/apimachinery/pkg/runtime/schema/generated.proto
  common-protos/k8s.io/apimachinery/pkg/util/intstr/generated.proto
  get_protos.sh
Labels: size/XXL

#545 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#546 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#547 Automator: update build-tools image@release-1.13 in istio/common-files@release-1.13
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#548 Automator: update build-tools image@release-1.12 in istio/common-files@release-1.12
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#549 [release-1.11] Update build image version
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#550 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#551 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#553 When updating shellcheck to 0.8 we get a new error; let's ignore it
  files/common/scripts/run.sh
Labels: size/XS

#540 Add support for kind dual-stack
  files/common/scripts/kind_provisioner.sh
Labels: size/XS

#554 write gencheck patch to artifacts
  files/common/scripts/check_clean_repo.sh
Labels: size/S

#552 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#555 Apply `go mod` commands to all modules
  files/common/Makefile.common.mk
Labels: size/XS

#556 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#557 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#558 Backport changes to standardize environment variables
  files/common/scripts/run.sh
  files/common/scripts/setup_env.sh
Labels: size/L

#559 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#561 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#562 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#563 Do not blocklist `GO` env vars
  files/common/scripts/setup_env.sh
Labels: size/XS

#564 Remove override of REPO_ROOT in build container
  files/common/scripts/setup_env.sh
Labels: size/XS

#565 common-protos: remove gogo
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/any.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/api.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/compiler/plugin.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/duration.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/empty.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/field_mask.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/source_context.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/struct.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/timestamp.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/type.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/wrappers.proto
  common-protos/gogoproto/gogo.proto
Labels: size/XXL, release-notes-none

#567 Revert "Remove override of REPO_ROOT in build container"
  files/common/scripts/setup_env.sh
Labels: size/XS

#566 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#568 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#569 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#570 Make ENV_BLOCKLIST more accurate
  files/common/scripts/setup_env.sh
Labels: size/XS
