Repository istio/common-files, pull requests merged in 2023-04, with the labels that each got.

#813 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#812 Add codespaces to common files
  files/.devcontainer/devcontainer.json
  files/common/Makefile.common.mk
Labels: size/S

#816 Update to only cp .devcontainer and .gitattributes on a Mac and not .* (seems to pick up parent)
  files/common/Makefile.common.mk
Labels: size/XS

#815 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#817 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#811 Added `ORG` to allow users to change the where common files sha comes from
  bin/update-build-image.sh
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/S

#814 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#818 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#819 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#821 [release-1.18] Automated branching step 5
  CODEOWNERS
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
