Repository istio/common-files, pull requests merged in 2023-07, with the labels that each got.

#873 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#877 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#876 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#875 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#874 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#878 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#881 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#882 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#880 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#883 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#885 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#884 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#887 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#886 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#888 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#889 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#891 Fix a typo in .golangci config
  files/common/config/.golangci.yml
Labels: size/XS, ok-to-test

#890 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#892 Move tracing script over
  files/common/scripts/tracing.sh
Labels: size/L

#894 Fixing tracing in periodic jobs
  files/common/scripts/tracing.sh
Labels: size/XS, release-notes-none

#893 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
