Repository istio/common-files, pull requests merged in 2023-11, with the labels that each got.

#950 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#949 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#952 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#951 Automator: update build-tools image@release-1.20 in istio/common-files@release-1.20
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#953 Bump metallb
  files/common/scripts/kind_provisioner.sh
  files/common/scripts/metallb-native.yaml
  files/common/scripts/metallb.yaml
Labels: size/XXL

#955 Move kind_provisoner default to k8s 1.28
  files/common/scripts/kind_provisioner.sh
Labels: size/XS
