Repository istio/common-files, pull requests merged in 2023-10, with the labels that each got.

#923 Update devcontainer.json
  files/.devcontainer/devcontainer.json
Labels: size/S

#922 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#924 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#925 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#926 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#928 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#929 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#927 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#930 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#931 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#933 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#932 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#934 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#935 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#939 Automation step 5 for release 1.20
  CODEOWNERS
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/XS

#937 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#941 Make some variables local
  files/common/scripts/kind_provisioner.sh
Labels: size/S

#942 Automator: update build-tools image@release-1.20 in istio/common-files@release-1.20
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#940 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#943 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#946 Allow dot usage in test files
  files/common/config/.golangci.yml
Labels: size/XS

#948 Update the license file to be unmodified apache license
  files/LICENSE
Labels: size/XS, ok-to-test
