Repository istio/common-files, pull requests merged in 2023-06, with the labels that each got.

#843 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#846 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#847 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#849 Update devcontainer.json
  files/.devcontainer/devcontainer.json
Labels: size/XS

#851 rm depguard/v1 settings
  files/common/config/.golangci.yml
Labels: size/XS

#852 Automator: update build-tools image@master in istio/common-files@master
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#850 Update devcontainer when updating the tools image
  bin/update-build-image.sh
Labels: size/XS

#853 Update devcontainer path
  bin/update-build-image.sh
Labels: size/XS

#855 Fix update_build_image to insert correct image
  bin/update-build-image.sh
Labels: size/XS

#854 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/S, release-notes-none

#856 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#857 Automator: update build-tools image@release-1.16 in istio/common-files@release-1.16
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#858 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#859 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#861 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#862 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#863 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#865 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#866 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#867 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#868 1.18: manual build tools update
  files/common/scripts/setup_env.sh
Labels: size/XS

#869 [release-1.16] Manual build-tools image update
  files/common/scripts/setup_env.sh
Labels: size/XS

#871 [release-1.17] Manual build-tools image update
  files/common/scripts/setup_env.sh
Labels: size/XS
