Repository istio/common-files, pull requests merged in 2023-08, with the labels that each got.

#896 Automator: update build-tools image@release-1.17 in istio/common-files@release-1.17
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#895 Automator: update build-tools image@release-1.18 in istio/common-files@release-1.18
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#897 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#899 [release-1.19] Automated branching step 5
  CODEOWNERS
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: release-notes-none

#900 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#901 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#902 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#903 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#906 Update golangci-lint-version to 1.54.x
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
Labels: size/XS

#904 volume for cargo git dir
  files/common/scripts/run.sh
Labels: size/XS

#905 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#907 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#908 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#909 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#910 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#911 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#912 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#913 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
