Repository istio/common-files, pull requests merged in 2024-06, with the labels that each got.

#1050 Silence more useless gRPC deprecations
  files/common/config/.golangci.yml
Labels: size/S, release-notes-none

#1051 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1052 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1053 Make it easy to use a stale build tool
  files/common/scripts/setup_env.sh
Labels: size/S, release-notes-none

#1055 Automator: update build-tools image@release-1.20 in istio/common-files@release-1.20
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1054 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1056 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1042 Automator: update build-tools image@release-1.22 in istio/common-files@release-1.22
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1043 Automator: update build-tools image@release-1.21 in istio/common-files@release-1.21
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1058 Update common files
  files/.devcontainer/devcontainer.json
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/XS

#1060 Update tools image
  files/.devcontainer/devcontainer.json
  files/common/scripts/check_clean_repo.sh
  files/common/scripts/setup_env.sh
Labels: size/XS

#1061 Fix integ-suite-kind.sh for deploying IPv6/dualStack clusters
  files/common/scripts/kind_provisioner.sh
Labels: size/S, ok-to-test
