Repository istio/common-files, pull requests merged in 2024-02, with the labels that each got.

#980 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#981 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#985 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#982 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#987 Master master update image version e8515a01
  files/.devcontainer/devcontainer.json
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
  files/common/scripts/setup_env.sh
Labels: size/XS

#989 Update SUPPORT.md to drop discuss.istio.io
  files/SUPPORT.md
Labels: size/XS

#990 add calico option to kind provisioning
  files/common/scripts/kind_provisioner.sh
Labels: size/M

#991 Add Google's Artifact Registry to trustedRegistries
  files/common/config/.hadolint.yml
Labels: size/XS

#992 Allow multi-region Artifact Registry
  files/common/config/.hadolint.yml
Labels: size/XS

#993 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#988 Automator: update build-tools image@release-1.21 in istio/common-files@release-1.21
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#994 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#995 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#983 Automator: update build-tools image@release-1.20 in istio/common-files@release-1.20
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#997 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#998 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
