Repository istio/common-files, pull requests merged in 2024-04, with the labels that each got.

#1012 Update .golangci.yml
  files/common/config/.golangci.yml
Labels: size/XS

#1013 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1018 Update golangci.yml to fix yaml errors
  files/common/config/.golangci.yml
Labels: size/M

#1017 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1019 Ignore grpc-go triggering annoying warnings
  files/common/config/.golangci.yml
Labels: size/XS

#1015 Automator: update build-tools image@release-1.20 in istio/common-files@release-1.20
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1014 Automator: update build-tools image@release-1.21 in istio/common-files@release-1.21
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1020 update gloangci-format.yml to match golangci.yml changes
  files/common/config/.golangci-format.yml
Labels: size/M

#1016 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1011 kind: Respect IP_FAMILY settings for non-default config as well
  files/common/scripts/kind_provisioner.sh
Labels: size/S

#1021 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1022 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1024 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1028 [release-1.22] Automated branching step 5
  CODEOWNERS
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1027 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1030 Automator: update build-tools image@release-1.22 in istio/common-files@release-1.22
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1031 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
