Repository istio/common-files, pull requests merged in 2024-03, with the labels that each got.

#999 Don't update the CCA license file during make update-common
  files/common/Makefile.common.mk
Labels: size/XS

#1000 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1001 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1002 Automator: update build-tools image@release-1.21 in istio/common-files@release-1.21
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1003 Automator: update build-tools image@release-1.20 in istio/common-files@release-1.20
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1004 Automator: update build-tools image@release-1.19 in istio/common-files@release-1.19
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1005 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1006 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1008 Prevent taint-related error from being printed by kind_provisioner.sh
  files/common/scripts/kind_provisioner.sh
Labels: size/XS, ok-to-test

#1009 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1010 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
