Repository istio/common-files, pull requests merged in 2025-01, with the labels that each got.

#1123 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1127 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS

#1128 Add missed license exception
  files/common/config/license-lint.yml
Labels: size/XS, release-notes-none

#1132 Another missing license
  files/common/config/license-lint.yml
Labels: size/XS

#1131 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1133 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1134 Automator: update build-tools image@release-1.24 in istio/common-files@release-1.24
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1135 rename IP_FAMILY to KIND_IP_FAMILY for better clarity
  files/common/scripts/kind_provisioner.sh
Labels: size/S

#1137 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1138 add DEVCONTAINER support to kind provisioner
  files/common/scripts/kind_provisioner.sh
Labels: size/XS

#1140 allow unset devcontainer var
  files/common/scripts/kind_provisioner.sh
Labels: size/XS

#1142 Update kind_provisioner.sh
  files/common/scripts/kind_provisioner.sh
Labels: size/XS
