Repository istio/common-files, pull requests merged in 2025-04, with the labels that each got.

#1165 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1168 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1169 Automator: update build-tools image@release-1.24 in istio/common-files@release-1.24
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1170 Automator: update build-tools image@release-1.23 in istio/common-files@release-1.23
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1167 bump golangci-lint to v2
  files/common/config/.golangci-format.yml
  files/common/config/.golangci.yml
  files/common/config/license-lint.yml
  files/common/scripts/format_go.sh
  files/common/scripts/lint_go.sh
Labels: size/XL

#1172 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1173 retrigger
  files/common/config/.golangci.yml
Labels: size/XS

#1171 Automator: update build-tools image@release-1.25 in istio/common-files@release-1.25
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1175 [release-1.26] Automated branching step 5
  CODEOWNERS
  files/common/Makefile.common.mk
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none

#1177 Automator: update build-tools image@master in istio/common-files@master
  files/.devcontainer/devcontainer.json
  files/common/scripts/setup_env.sh
Labels: size/XS, release-notes-none
